ResNet18 full training
torchrun --nproc_per_node=1  train.py --model=resnet18 --data-path=/n/holystore01/LABS/barak_lab/Everyone/datasets/imagenet256 -b=256 --output-dir=/n/holyscratch01/barak_lab/Lab/sqin/invariance/experts/ResNet18 --print-freq=100
[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
[W socket.cpp:426] [c10d] The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
[E socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "/n/holylabs/LABS/barak_lab/Lab/sqin/envs/invariance/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 844, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 678, in _initialize_workers
    self._rendezvous(worker_group)
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 538, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/n/home05/sqin/.conda/envs/invariance/lib/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
